openapi: "3.0.0"
info:
  version: 1.0.0
  title: Rest App
tags:
  - name: groups
    description: Groups
paths:
  /groups:
    get:
      tags:
        - groups
      summary: List groups
      operationId: getGroupsByParams
      parameters:
        - name: params
          in: query
          description: List groups params
          required: true
          schema:
            $ref: "#/components/schemas/GroupParams"
      responses:
        '200':
          description: List groups
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListGroup"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /groups/{groupId}:
    get:
      summary: Info for a specific group
      operationId: getGroupById
      tags:
        - groups
      parameters:
        - name: groupId
          in: path
          required: true
          description: The id of the group to retrieve
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Group
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GroupResponse"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  schemas:

    GroupParams:
      required:
        - page
        - size
      properties:
        page:
          type: integer
          format: int32
          minimum: 1
        size:
          type: integer
          format: int32
          minimum: 1
          maximum: 150
        id:
          type: array
          items:
            type: string
            format: uuid
          maxItems: 100
        notId:
          type: array
          items:
            type: string
            format: uuid
          maxItems: 100
        isActive:
          type: boolean

    GroupResponse:
      required:
        - id
        - name
        - isActive
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        isActive:
          type: string

    ListGroup:
      required:
        - total
        - groups
      properties:
        total:
          type: string
        groups:
          type: array
          items:
            $ref: "#/components/schemas/GroupResponse"

    ErrorResponse:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string